### ISSUE TITLE
Make doesn't succeed without static or default .css

### ISSUE THREAD

**Issue by Salt-Factory** [ozy/makefile-blog#1]
Hi,

I've been looking for a minimalist way of generating website pages, so naturally I tried out this project.
When following the README however, an error was thrown:

```
cp: cannot stat 'posts/static/*': No such file or directory
make: *** [makefile:126: static_content] Error 1
```

After creating a dummy file at `posts/static/dummy`, I was presented with the following error:

```
cp: cannot stat 'templates/default/*.css': No such file or directory
```

**Comment by ozy** [comment]
Thanks for the heads up. Cp errors now suppressed & showing info instead. Issue resolved in [4226aa0](https://github.com/ozy/makefile-blog/commit/4226aa0ab0ee3aa3881ba25907baa163104332b8)
