### ISSUE TITLE
Generate other pages

### ISSUE THREAD

**Issue by Salt-Factory** [ozy/makefile-blog#2]
Hello again,

I would like to use this software for my small, personal website.
So far, I've been able to create my own template which looks the same like my website does now.
One problem I have is that I want to add other pages than index.html and posts.
How could I go about this? 

Thanks in advance,
Simon

**Comment by ozy** [comment]
Hi,

That's a valid concern that I have too. I'm planning to work over it this weekend. If you would like to implement it yourself and asking my opinion about it, I would add a separate directory for pages and a menu_item template file for putting links to the header. So, with the default template, content of the menu_item.html would be roughly similar to:
```<li><a href="${TEMPLATE_BLOG_ROOT}/${TEMPLATE_PAGES_DIR}/${TEMPLATE_PAGE_URL}">${TEMPLATE_PAGE_NAME}</a></li>```
which will be enumared and put next to the static links:
```
    <div class="header">
      <div class="mainbar center">
        <ul>
          <li><a href="${TEMPLATE_BLOG_ROOT}/">Index Page</a></li>
          <li><a href="${TEMPLATE_BLOG_ROOT}/posts/">Posts</a></li>
          <li><a rel="alternate" type="application/rss+xml" href="${TEMPLATE_BLOG_ROOT}/RSS.xml">RSS</a></li>
${TEMPLATE_MENU_ITEMS}
        </ul>
      </div>
    </div>
```

Apart from this, it's pretty straightforward. Getting pages with find and building them individually similar to building process of posts. Probably post building rules can be generalized to pages too.

**Comment by Salt-Factory** [comment]
Cool! I might fiddle around to learn how it would work, but I do not trust myself enough yet to implement it. 

Thanks againfor your work on this project. :-)
