### ISSUE TITLE
Make setup results in error

### ISSUE THREAD

**Issue by Salt-Factory** [ozy/makefile-blog#4]
Hi,

I tried creating a new project from scratch, so after cloning I ran `make setup`, as listed in the README.
This resulted in the following error:

```
find: ‘posts’: No such file or directory
find: ‘pages’: No such file or directory
makefile:38: *** No blog post found under posts.  Stop.
```
If I understand correctly, make tries to find the directories before they were created.

Thanks,
Simon

**Comment by ozy** [comment]
Can you check prereq branch and confirm?

**Comment by Salt-Factory** [comment]
I can confirm that it works now. :-)
