### ISSUE TITLE
What is the license?

### ISSUE THREAD

**Issue by klardotsh** [ozy/makefile-blog#6]
Hey there! This project looks awesome and I'd love to derive from it to make my personal site (long overdue...), but I don't see any licensing information in the source tree - what are the `COPYING` terms? So far in my README I've attributed this upstream repo, but before distributing my source anywhere I'd like to make sure everything is in the legal clear.

Cheers!

**Comment by ozy** [comment]
Hey, I was thinking of GPL. What's your opinion about it / does it limit what you have in your mind?

**Comment by klardotsh** [comment]
If you feel GPL is the correct license, then license it GPL, don't worry about what I think of it :)

That said I'm also completely fine with GPL on the Makefiles (my blog posts and other site content were going to be `CC-BY-SA 4.0` anyway, so copyleft on the tools used to render them seems appropriate!)
